version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manu123
      POSTGRES_DB: nextcart
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/db  # cartella con il dump
    ports:
      - "5432:5432"

  restore:
    image: postgres:17-alpine
    container_name: nextcart_restore
    depends_on:
      - postgres
    environment:
      PGPASSWORD: manu123
    volumes:
      - ./db:/db
    command: >
      sh -c "pg_restore --verbose --clean --no-acl --no-owner -h postgres -U postgres -d nextcart /db/nextcart.dump"
    # Questo servizio lo userai solo per il restore e poi puoi rimuoverlo/commentarlo

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: nextcart_api
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: manu123
      DATABASE_NAME: nextcart
      JWT_SECRET: supersegreto123
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    container_name: nextcart_web
    ports:
      - "4200:80"
    depends_on:
      - api
  web-user:
    build:
      context: .
      dockerfile: apps/website-user/Dockerfile
    container_name: nextcart_web_user
    ports:
      - "4300:80"
    depends_on:
      - api

volumes:
  postgres_data:
